name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        
    - name: Login to ECR registry
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ vars.ECR_REGISTRY_ID }}
      
    - name: Build and push to ECR
      env:
        ECR_REGISTRY: ${{ vars.ECR_REGISTRY_ID }}
        ECR_REPOSITORY: prova-gh-actions
        IMAGE_TAG: 1.0.0
      run: |
        docker build --tag $ECR_REGISTRY.dkr.ecr.eu-west-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY.dkr.ecr.eu-west-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
